version: "3"

services:
  nuxt:
    image: marcell17002/noesantara-web:latest
    container_name: coffee_website
    
  nginx:
    image: marcell17002/noesantara-web-nginx:latest
    container_name: coffee_website_nginx
    ports: 
      - 80:80
    depends_on: 
      - nuxt